import React from "react";
import Head from "next/head";
import { Navbar, Footer } from "../components/Layout";
import { AnimatedBackground } from "../components/AnimatedBackground";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background flex flex-col selection:bg-primary/20 selection:text-primary">
      <Head>
        <title>Privacy Policy | Senzor</title>
        <meta
          name="description"
          content="Privacy Policy and Data Processing protocols for Senzor platforms."
        />
      </Head>

      <Navbar />

      <main className="flex-grow pt-32 pb-24 relative overflow-hidden">
        <AnimatedBackground />

        {/* Subtle Background Glow */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-primary/5 rounded-full blur-[120px] pointer-events-none -z-10" />

        <div className="max-w-4xl mx-auto px-4 md:px-8 relative z-10">
          <div className="mb-12 border-b border-border/40 pb-8">
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tighter text-foreground mb-4">
              Privacy Policy
            </h1>
            <p className="text-muted-foreground font-mono text-sm tracking-wide uppercase">
              Effective Date: April 5, 2026
            </p>
          </div>

          <div className="space-y-10 text-base leading-relaxed text-muted-foreground">
            <section className="space-y-4">
              <p className="text-lg font-medium text-foreground">
                Senzor Platforms Inc. ("Senzor", "we", "us", or "our") is
                committed to protecting the privacy and security of the data
                entrusted to us. This Privacy Policy outlines our practices
                regarding the collection, processing, and disclosure of
                information when you use our observability platform, agents, and
                APIs (collectively, the "Service").
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                1. Dual Capacity: Controller & Processor
              </h2>
              <p>
                To comply with global data protection frameworks, including the
                General Data Protection Regulation (GDPR) and the California
                Consumer Privacy Act (CCPA), Senzor operates in two distinct
                capacities:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Data Controller:</strong> For the administrative data
                  you provide to create a Senzor account, manage billing, and
                  interact with our support teams.
                </li>
                <li>
                  <strong>Data Processor:</strong> For the operational telemetry
                  data (logs, traces, metrics, RUM data) generated by your
                  applications and transmitted to our ingestion APIs. You, the
                  Customer, remain the Data Controller for this information.
                </li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                2. Information Collection
              </h2>
              <h3 className="text-lg font-semibold text-foreground mt-4">
                A. Account & Administrative Data
              </h3>
              <p>
                When you register, we collect necessary administrative data,
                including your email address, name, and authentication
                credentials (secured via Firebase Auth). If you upgrade to a
                paid tier, your financial information is collected and processed
                securely by our Merchant of Record, Paddle.com. Senzor does not
                store, process, or transmit full credit card numbers on our
                infrastructure.
              </p>

              <h3 className="text-lg font-semibold text-foreground mt-4">
                B. Operational Telemetry Data
              </h3>
              <p>
                We ingest data generated by your integrated systems. This may
                include IP addresses, user agents, API performance metrics,
                server resource utilization, and application logs.
              </p>
              <div className="bg-destructive/10 border border-destructive/20 p-4 rounded-md text-destructive mt-4">
                <strong>Strict Prohibition:</strong> You are contractually
                prohibited from transmitting Personally Identifiable Information
                (PII), Protected Health Information (PHI), or Payment Card
                Industry (PCI) data within your custom telemetry payloads, logs,
                or traces to the Senzor platform.
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                3. Utilization of Information
              </h2>
              <p>
                Senzor utilizes collected data strictly for the following
                purposes:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  To provision, maintain, and secure the Senzor observability
                  platform.
                </li>
                <li>
                  To meter ingestion usage and enforce applicable subscription
                  quotas.
                </li>
                <li>
                  To detect, prevent, and mitigate unauthorized access or
                  malicious network activity.
                </li>
                <li>
                  To communicate operational alerts, security advisories, and
                  administrative updates.
                </li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                4. Data Sharing & Subprocessors
              </h2>
              <p>
                Senzor does not sell personal information or telemetry data. We
                share data solely with vetted, enterprise-grade subprocessors
                required to deliver the Service. Our primary subprocessors
                include:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Cloud Infrastructure:</strong> Core database and
                  compute hosting.
                </li>
                <li>
                  <strong>Paddle.com:</strong> Merchant of Record for
                  subscription management and global tax compliance.
                </li>
                <li>
                  <strong>Google Firebase:</strong> Identity and access
                  management (IAM).
                </li>
              </ul>
              <p>
                A complete, up-to-date list of subprocessors is available to
                Enterprise customers upon request.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                5. Data Retention & Lifecycle
              </h2>
              <p>
                <strong>Administrative Data:</strong> Retained for the duration
                of your active account lifecycle. Upon account deletion,
                administrative data is purged within 30 days, excluding data
                required for legal or tax compliance.
              </p>
              <p>
                <strong>Telemetry Data:</strong> Operational telemetry is
                strictly ephemeral. It is automatically and permanently expunged
                from our databases on a rolling basis, dictated by your
                subscription tier's retention policy (e.g., 3, 15, or 30 days).
                Once the retention window lapses, data is cryptographically
                unrecoverable.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                6. International Data Transfers
              </h2>
              <p>
                Senzor operates globally. If you reside in the European Economic
                Area (EEA), the UK, or Switzerland, your data may be transferred
                to, and processed in, the United States. We ensure such
                transfers are protected by appropriate safeguards, including the
                execution of Standard Contractual Clauses (SCCs) as approved by
                the European Commission.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                7. Security Posture
              </h2>
              <p>
                We employ defense-in-depth security methodologies. All telemetry
                and administrative data is encrypted in transit using TLS 1.3.
                Database volumes, credentials, and API keys are encrypted at
                rest using AES-256. Access to production infrastructure is
                strictly audited and limited to authorized personnel via
                zero-trust network access controls.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">
                8. Contact & Data Subject Rights
              </h2>
              <p>
                Depending on your jurisdiction, you maintain the right to
                access, rectify, erase, or restrict the processing of your
                personal data. To exercise these rights, or to contact our Data
                Protection Officer (DPO), please email:
              </p>
              <p className="font-mono font-medium text-foreground">
                privacy@senzor.dev
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
